### ISSUE TITLE
please add korean font

### ISSUE THREAD

**Issue by hogamm** [amazfitbip/font#5]
hello 

i want to know korean font can be added.
korean font consists of 11172 characters.
i hope that you can add it.

i attatched korean font below. 
i downloaded it from facebook(xiaomi huami amazfit bip internayional group)

thanks

[Korean(Hangul)font.zip](https://github.com/amazfitbip/font/files/1693410/Korean.Hangul.font.zip)

**Comment by yener90** [comment]
1. Images seems to be broken.
2. Sizes are not 16x16

**Comment by hogamm** [comment]
thank you for response.

i uploaded new one. i checked images and images's size.
please add it.

[korean_font.zip](https://github.com/amazfitbip/font/files/1698077/korean_font.zip)

and if you add it successfully,how can i download .ft file?

thank you for your effort.

and i attatched bmpfont source which above bmp font made by it. it is simple java code.
[BmpFontMaker.zip](https://github.com/amazfitbip/font/files/1698082/BmpFontMaker.zip)

**Comment by hogamm** [comment]
i made a korean font with your python tool. thanks
